#:schema node_modules/wrangler/config-schema.json
name = "route-dog-dev"
main = "src/index.ts"
compatibility_date = "2026-01-17"

[observability]
enabled = true

# Environment-specific configurations
[env.dev]
name = "route-dog-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "route-dog-prod"
vars = { ENVIRONMENT = "production" }

